### ISSUE TITLE
"Waiting for the text recognition model to be downloaded" fails

### ISSUE THREAD

**Issue by edo0** [mtotschnig/OCR#2]
I have just tried for the first time the OCR function on my device. Specifically I run:
* Lineage OS 16 - Android 9  
* without Play Services, and instead microG (0.2.10.19420)

Since my version of MyExpenses was downloaded from F-droid, I went on to download the OCR reader companion app.
Unfortunately the same warning message is displayed every time I try to scan a receipt

[Picture](https://www.brogiolo.eu/nextcloud/s/r79d6mRjDbMNZz4) 

Here is a [logcat](https://www.brogiolo.eu/nextcloud/s/JxWBKC4meNKmMkd)  I have capture in one of the occasions

**Comment by mtotschnig** [comment]
I suppose that microg does not implement the feature that mlkit needs from Play Services, i.e. download of the model that it uses for text recognition. Unfortunately, there does not seem to be an option to include that model directly into the app.
So Google-free phones would need to wait for the planned alternative implementation based on Tesseract.

**Comment by mtotschnig** [comment]
I am closing this, since a version based on Tesseract is now available.
