### ISSUE TITLE
Unable to copy results

### ISSUE THREAD

**Issue by luismanriqueruiz** [mtotschnig/OCR#3]
I'm unable to copy the result of the OCR. There is no button nor any other way to copy results from that window to different apps.

**Comment by mtotschnig** [comment]
Thank you for the suggestion. Originally I have written this application so that other applications can call it via Intents. But of course, it makes sense to allow users to copy the result via the clipboard. I will add this for version 3.

**Comment by luismanriqueruiz** [comment]
Nice app, and thanks for improving it!
