### ISSUE TITLE
How to install languages on the Tesseract version?

### ISSUE THREAD

**Issue by lrq3000** [mtotschnig/OCR#8]
The app says that the language files are not yet downloaded, how can I do that?

Thank you very much for this software, it would be awesome to be able to use Tesseract on Android!

**Comment by mtotschnig** [comment]
When you open the app, click on language, and select the language you want to use, the model data should be downloaded.

**Comment by lrq3000** [comment]
This works as you described, thank you @mtotschnig

**Comment by mtotschnig** [comment]
Discussion with user on DivestOS:
Me: it seems that DivestOS allows to configure if an app is allowed to access the Internet. Could you verify if this permission is granted to the OCR app?
User: Good news, it's fixed! You were on the right track, I found out that to download the model your app invokes Androids "Download Manager" in the background, which did in fact have network permissions off. Model downloaded, thanks!
